---
version: "3.8"

services:
  nautobot:
    environment:
      - "NAUTOBOT_DB_ENGINE=django.db.backends.mysql"
    env_file:
      - "development.env"
      - "creds.env"
      - "development_dolt.env"
  worker:
    environment:
      - "NAUTOBOT_DB_ENGINE=django.db.backends.mysql"
    env_file:
      - "development.env"
      - "creds.env"
      - "development_dolt.env"
  db:
    build:
      context: "../"
      dockerfile: "development/Dockerfile-dolt"
    command:
      - "dolt"
      - "--ignore-lock-file"
      - "sql-server"
      - "--config=/dolt-config.yaml"
      # - "--default-authentication-plugin=mysql_native_password"
    env_file:
      - "development.env"
      - "creds.env"
      - "development_dolt.env"
    volumes:
      - "dolt_data:/var/lib/nautobot"
      - "./dolt-config.yaml:/dolt-config.yaml"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: "20s"
      retries: 10

volumes:
  dolt_data: {}
